from .scheme import SchemeAdmin
from .access import AccessAdmin
from .user import UserAdmin
from .building import BuildingAdmin
from .room import RoomAdmin
from .server_rack import ServerRackAdmin
from .unit import UnitAdmin
from .type_port import TypePortAdmin
from .manufacturer import ManufacturerAdmin
from .sfp_template import SfpTemplateAdmin
from .equipment_template import EquipmentTemplateAdmin
from .port_template import PortTemplateAdmin
from .equipment import EquipmentAdmin
from .port import PortAdmin
from .line_type import LineTypeAdmin
from .line import LineAdmin
