# Generated by Django 5.0.6 on 2024-05-25 14:15

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(max_length=100, verbose_name="Номер корпуса"),
                ),
            ],
            options={
                "verbose_name": "Корпус",
                "verbose_name_plural": "Корпусы",
            },
        ),
        migrations.CreateModel(
            name="EquipmentTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Switch", "Коммутатор"),
                            ("Server", "Сервер"),
                            ("Passive", "Пассивное оборудование"),
                        ],
                        max_length=100,
                        verbose_name="Тип оборудования",
                    ),
                ),
                ("model", models.CharField(max_length=100, verbose_name="Модель")),
                ("power", models.IntegerField(null=True, verbose_name="Мощность")),
                (
                    "number_of_units",
                    models.IntegerField(verbose_name="Количество занимаемых юнитов"),
                ),
            ],
            options={
                "verbose_name": "Шаблон оборудования",
                "verbose_name_plural": "Шаблоны оборудований",
            },
        ),
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Имя производителя"),
                ),
            ],
            options={
                "verbose_name": "Производитель",
                "verbose_name_plural": "Производители",
            },
        ),
        migrations.CreateModel(
            name="PortTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Наименование")),
            ],
            options={
                "verbose_name": "Шаблон порта",
                "verbose_name_plural": "Шаблоны портов",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment",
                        to="models_app.equipmenttemplate",
                        verbose_name="Шаблон",
                    ),
                ),
            ],
            options={
                "verbose_name": "Оборудование",
                "verbose_name_plural": "Оборудования",
            },
        ),
        migrations.AddField(
            model_name="equipmenttemplate",
            name="manufacturer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="equpment_template",
                to="models_app.manufacturer",
                verbose_name="Производитель",
            ),
        ),
        migrations.CreateModel(
            name="Port",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.IntegerField(verbose_name="Номер порта в оборудовании")),
                (
                    "line_type",
                    models.CharField(
                        choices=[
                            ("Ethernet", "Медный провод"),
                            ("multi_mode", "Многомодовый"),
                            ("None", "None"),
                            ("single-mode", "Одномодовый"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Тип линии",
                    ),
                ),
                (
                    "vlan_type",
                    models.CharField(
                        choices=[
                            ("Access", "Access"),
                            ("None", "None"),
                            ("Trunk", "Trunk"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Тип vlan",
                    ),
                ),
                (
                    "vlan",
                    models.IntegerField(
                        null=True, verbose_name="Vlan на котором работает порт"
                    ),
                ),
                (
                    "ip",
                    models.CharField(
                        max_length=150, null=True, verbose_name="IP адрес"
                    ),
                ),
                (
                    "mac",
                    models.CharField(
                        max_length=150, null=True, verbose_name="Mac адрес"
                    ),
                ),
                (
                    "connection",
                    models.IntegerField(null=True, verbose_name="Подключение к порту"),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="port",
                        to="models_app.equipment",
                        verbose_name="Оборудование",
                    ),
                ),
            ],
            options={
                "verbose_name": "Порт",
                "verbose_name_plural": "Порты",
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(max_length=100, verbose_name="Номер комнаты"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("Regular", "Обычная"), ("Server", "Серверная")],
                        max_length=100,
                        verbose_name="Тип комнаты",
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room",
                        to="models_app.building",
                        verbose_name="Корпус",
                    ),
                ),
            ],
            options={
                "verbose_name": "Комната",
                "verbose_name_plural": "Комнаты",
            },
        ),
        migrations.CreateModel(
            name="Scheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(null=True, verbose_name="Номер схемы")),
                (
                    "title",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Назавние"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schema",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель схемы",
                    ),
                ),
            ],
            options={
                "verbose_name": "Схема",
                "verbose_name_plural": "Схемы",
            },
        ),
        migrations.AddField(
            model_name="building",
            name="scheme",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="building",
                to="models_app.scheme",
                verbose_name="схема",
            ),
        ),
        migrations.CreateModel(
            name="Access",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("Change", "Изменение"), ("Read", "Чтение")],
                        max_length=100,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheme",
                        to="models_app.scheme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Доступ",
                "verbose_name_plural": "Доступы",
            },
        ),
        migrations.CreateModel(
            name="ServerRack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number_of_units",
                    models.IntegerField(verbose_name="Количетсво юнитов"),
                ),
                ("title", models.CharField(max_length=100)),
                ("max_power", models.IntegerField(null=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="server_rack",
                        to="models_app.room",
                        verbose_name="Комната",
                    ),
                ),
            ],
            options={
                "verbose_name": "Стойка",
                "verbose_name_plural": "Стойки",
            },
        ),
        migrations.CreateModel(
            name="SfpTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="port_template",
                        to="models_app.manufacturer",
                        verbose_name="Производитель",
                    ),
                ),
                (
                    "port_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="port_template",
                        to="models_app.porttemplate",
                        verbose_name="Форм-фактор",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SpeedTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "speed",
                    models.IntegerField(
                        null=django.db.models.deletion.CASCADE,
                        verbose_name="Скорость порта",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[("Gb", "Gb"), ("Kb", "Kb"), ("Mb", "Mb")],
                        max_length=50,
                        verbose_name="Единица измерения",
                    ),
                ),
                (
                    "port_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="port_template",
                        to="models_app.porttemplate",
                        verbose_name="Шаблон порта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Шаблон скорости порта",
                "verbose_name_plural": "Шаблоны скоростей портов",
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.IntegerField(verbose_name="Номер юнита в стойке")),
                (
                    "side",
                    models.CharField(
                        choices=[("Back", "Тыльная"), ("Front", "Лицевая")],
                        max_length=100,
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unit",
                        to="models_app.equipment",
                        verbose_name="Оборудование",
                    ),
                ),
                (
                    "server_rack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unit",
                        to="models_app.serverrack",
                        verbose_name="Стойка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Юнит",
                "verbose_name_plural": "Юниты",
            },
        ),
    ]
