# Generated by Django 5.1.1 on 2024-12-18 13:03

import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import models_app.models.mixins.show_model_info_mixin
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Номер корпуса"),
                ),
                (
                    "coord_x",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Координата X на схеме"
                    ),
                ),
                (
                    "coord_y",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Координата Y на схеме"
                    ),
                ),
            ],
            options={
                "verbose_name": "Корпус",
                "verbose_name_plural": "Корпусы",
                "db_table": "building",
            },
            bases=(
                models.Model,
                models_app.models.mixins.show_model_info_mixin.ShowModelInfoMixin,
            ),
        ),
        migrations.CreateModel(
            name="EquipmentTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "model",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Модель"
                    ),
                ),
                (
                    "power",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Мощность"
                    ),
                ),
                (
                    "number_of_units",
                    models.PositiveIntegerField(
                        verbose_name="Количество занимаемых юнитов"
                    ),
                ),
                (
                    "count_port",
                    models.IntegerField(default=0, verbose_name="Количество портов"),
                ),
            ],
            options={
                "verbose_name": "Шаблон оборудования",
                "verbose_name_plural": "Шаблоны оборудований",
                "db_table": "equipment_template",
            },
            bases=(
                models.Model,
                models_app.models.mixins.show_model_info_mixin.ShowModelInfoMixin,
            ),
        ),
        migrations.CreateModel(
            name="EquipmentTemplateType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("is_active", models.BooleanField()),
            ],
            options={
                "verbose_name": "Тип оборудования",
                "verbose_name_plural": "Типы оборудований",
                "db_table": "equipment_template_type",
            },
            bases=(
                models.Model,
                models_app.models.mixins.show_model_info_mixin.ShowModelInfoMixin,
            ),
        ),
        migrations.CreateModel(
            name="LineType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Тип линии",
                "verbose_name_plural": "Тип линии",
                "db_table": "line_types",
            },
            bases=(
                models.Model,
                models_app.models.mixins.show_model_info_mixin.ShowModelInfoMixin,
            ),
        ),
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Имя производителя"
                    ),
                ),
            ],
            options={
                "verbose_name": "Производитель",
                "verbose_name_plural": "Производители",
                "db_table": "manufacturer",
            },
            bases=(
                models.Model,
                models_app.models.mixins.show_model_info_mixin.ShowModelInfoMixin,
            ),
        ),
        migrations.CreateModel(
            name="PortMode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("is_only_one_vlan", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Мод порта",
                "verbose_name_plural": "Моды портов",
                "db_table": "port_mode",
            },
            bases=(
                models.Model,
                models_app.models.mixins.show_model_info_mixin.ShowModelInfoMixin,
            ),
        ),
        migrations.CreateModel(
            name="Speed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "value",
                    models.PositiveBigIntegerField(
                        unique=True, verbose_name="Значение скорости"
                    ),
                ),
            ],
            options={
                "verbose_name": "Скорость передачи данных",
                "verbose_name_plural": "Скорости передачи данных",
                "db_table": "speed",
            },
            bases=(
                models.Model,
                models_app.models.mixins.show_model_info_mixin.ShowModelInfoMixin,
            ),
        ),
        migrations.CreateModel(
            name="TypePort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Наименование"
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип портов",
                "verbose_name_plural": "Типы портов",
                "db_table": "type_port",
            },
            bases=(
                models.Model,
                models_app.models.mixins.show_model_info_mixin.ShowModelInfoMixin,
            ),
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
                "db_table": "user",
            },
            bases=(
                models.Model,
                models_app.models.mixins.show_model_info_mixin.ShowModelInfoMixin,
            ),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "free_ports",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество свободных портов"
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipments",
                        related_query_name="equipment",
                        to="models_app.equipmenttemplate",
                        verbose_name="Шаблон",
                    ),
                ),
            ],
            options={
                "verbose_name": "Оборудование",
                "verbose_name_plural": "Оборудования",
                "db_table": "equipment",
            },
            bases=(
                models.Model,
                models_app.models.mixins.show_model_info_mixin.ShowModelInfoMixin,
            ),
        ),
        migrations.AddField(
            model_name="equipmenttemplate",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="equipment_templates",
                related_query_name="equipment_template",
                to="models_app.equipmenttemplatetype",
            ),
        ),
        migrations.CreateModel(
            name="Line",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("filled_line", models.BooleanField(blank=True, default=False)),
                (
                    "line_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lines",
                        related_query_name="line",
                        to="models_app.linetype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Линия",
                "verbose_name_plural": "Линии",
                "db_table": "lines",
            },
            bases=(
                models.Model,
                models_app.models.mixins.show_model_info_mixin.ShowModelInfoMixin,
            ),
        ),
        migrations.AddField(
            model_name="equipmenttemplate",
            name="manufacturer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="equipment_templates",
                related_query_name="equipment_template",
                to="models_app.manufacturer",
                verbose_name="Производитель",
            ),
        ),
        migrations.CreateModel(
            name="PortTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Наименование",
                    ),
                ),
                ("modular", models.BooleanField(blank=True, default=False)),
                (
                    "line_type",
                    models.ManyToManyField(
                        related_name="port_templates",
                        related_query_name="port_template",
                        to="models_app.linetype",
                        verbose_name="Потдерживаемы типы лииний",
                    ),
                ),
                (
                    "speed",
                    models.ManyToManyField(
                        db_table="port_speed",
                        related_name="port_templates",
                        related_query_name="port_template",
                        to="models_app.speed",
                    ),
                ),
                (
                    "type_port",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="port_templates",
                        related_query_name="port_template",
                        to="models_app.typeport",
                        verbose_name="Тип порта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Шаблон порта",
                "verbose_name_plural": "Шаблоны портов",
                "db_table": "port_template",
            },
            bases=(
                models.Model,
                models_app.models.mixins.show_model_info_mixin.ShowModelInfoMixin,
            ),
        ),
        migrations.CreateModel(
            name="PortShip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("count", models.IntegerField()),
                (
                    "unit",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                        verbose_name="В каком юните расположен",
                    ),
                ),
                (
                    "lines",
                    models.IntegerField(
                        default=2, null=True, verbose_name="Количество занимаемых линий"
                    ),
                ),
                (
                    "equipment_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="models_app.equipmenttemplate",
                    ),
                ),
                (
                    "port_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="models_app.porttemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Промежуточная таблица портов",
                "verbose_name_plural": "Промежуточная таблица портов",
                "db_table": "port_ship",
                "unique_together": {("equipment_template", "port_template")},
            },
            bases=(
                models.Model,
                models_app.models.mixins.show_model_info_mixin.ShowModelInfoMixin,
            ),
        ),
        migrations.AddField(
            model_name="equipmenttemplate",
            name="port",
            field=models.ManyToManyField(
                through="models_app.PortShip", to="models_app.porttemplate"
            ),
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "number",
                    models.CharField(max_length=100, verbose_name="Номер комнаты"),
                ),
                ("is_server_room", models.BooleanField()),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        related_query_name="room",
                        to="models_app.building",
                        verbose_name="Корпус",
                    ),
                ),
            ],
            options={
                "verbose_name": "Комната",
                "verbose_name_plural": "Комнаты",
                "db_table": "room",
            },
            bases=(
                models.Model,
                models_app.models.mixins.show_model_info_mixin.ShowModelInfoMixin,
            ),
        ),
        migrations.CreateModel(
            name="Scheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schemes",
                        related_query_name="scheme",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель схемы",
                    ),
                ),
            ],
            options={
                "verbose_name": "Схема",
                "verbose_name_plural": "Схемы",
                "db_table": "scheme",
            },
            bases=(
                models.Model,
                models_app.models.mixins.show_model_info_mixin.ShowModelInfoMixin,
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="scheme",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buildings",
                related_query_name="building",
                to="models_app.scheme",
                verbose_name="схема",
            ),
        ),
        migrations.CreateModel(
            name="Access",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Read", "Чтение"),
                            ("Change", "Изменение"),
                            ("Creator", "Создатель"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access",
                        related_query_name="access",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access",
                        related_query_name="access",
                        to="models_app.scheme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Доступ",
                "verbose_name_plural": "Доступы",
                "db_table": "access",
            },
            bases=(
                models.Model,
                models_app.models.mixins.show_model_info_mixin.ShowModelInfoMixin,
            ),
        ),
        migrations.CreateModel(
            name="Segment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="Имя сегмента")),
                (
                    "scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        related_query_name="segment",
                        to="models_app.scheme",
                        verbose_name="схема",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сегмент",
                "verbose_name_plural": "Сегменты",
                "db_table": "segment",
            },
            bases=(
                models.Model,
                models_app.models.mixins.show_model_info_mixin.ShowModelInfoMixin,
            ),
        ),
        migrations.CreateModel(
            name="ServerRack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "number_of_units",
                    models.IntegerField(verbose_name="Количетсво юнитов"),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "max_power",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="Максимальная мощность"
                    ),
                ),
                (
                    "free_power",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="Свободноя мощность"
                    ),
                ),
                (
                    "free_units",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Свободные юниты"
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="server_racks",
                        related_query_name="server_rack",
                        to="models_app.room",
                        verbose_name="Комната",
                    ),
                ),
            ],
            options={
                "verbose_name": "Стойка",
                "verbose_name_plural": "Стойки",
                "db_table": "server_rack",
            },
            bases=(
                models.Model,
                models_app.models.mixins.show_model_info_mixin.ShowModelInfoMixin,
            ),
        ),
        migrations.CreateModel(
            name="SfpTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Наименование"
                    ),
                ),
                (
                    "line_type",
                    models.ManyToManyField(
                        related_name="sfp_templates",
                        related_query_name="sfp_template",
                        to="models_app.linetype",
                        verbose_name="Потдерживаемы типы лииний",
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sfp_templates",
                        related_query_name="sfp_template",
                        to="models_app.manufacturer",
                        verbose_name="Производитель",
                    ),
                ),
                (
                    "speed",
                    models.ManyToManyField(
                        db_table="sfp_speed",
                        related_name="sfp_templates",
                        related_query_name="sfp_template",
                        to="models_app.speed",
                    ),
                ),
                (
                    "type_port",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sfp_templates",
                        related_query_name="sfp_template",
                        to="models_app.typeport",
                        verbose_name="Тип порта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sfp шаблон",
                "verbose_name_plural": "Sfp шаблоны",
                "db_table": "sfp_template",
            },
            bases=(
                models.Model,
                models_app.models.mixins.show_model_info_mixin.ShowModelInfoMixin,
            ),
        ),
        migrations.CreateModel(
            name="Port",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uid", models.IntegerField(verbose_name="Номер порта в оборудовании")),
                (
                    "mac",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Mac адрес"
                    ),
                ),
                (
                    "back_side",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="back",
                        to="models_app.port",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ports",
                        related_query_name="port",
                        to="models_app.equipment",
                        verbose_name="Оборудование",
                    ),
                ),
                (
                    "front_side",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="front",
                        to="models_app.port",
                    ),
                ),
                (
                    "line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ports",
                        related_query_name="ports",
                        to="models_app.line",
                    ),
                ),
                (
                    "mode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ports",
                        related_query_name="port",
                        to="models_app.portmode",
                    ),
                ),
                (
                    "port_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ports",
                        related_query_name="port",
                        to="models_app.porttemplate",
                        verbose_name="Шаблон порта",
                    ),
                ),
                (
                    "sfp",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ports",
                        related_query_name="port",
                        to="models_app.sfptemplate",
                        verbose_name="sfp",
                    ),
                ),
            ],
            options={
                "verbose_name": "Порт",
                "verbose_name_plural": "Порты",
                "db_table": "port",
            },
            bases=(
                models.Model,
                models_app.models.mixins.show_model_info_mixin.ShowModelInfoMixin,
            ),
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uid", models.IntegerField(verbose_name="Номер юнита в стойке")),
                (
                    "side",
                    models.CharField(
                        choices=[("Front", "Лицевая"), ("Back", "Тыльная")],
                        max_length=100,
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="unit",
                        related_query_name="units",
                        to="models_app.equipment",
                        verbose_name="Оборудование",
                    ),
                ),
                (
                    "server_rack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        related_query_name="unit",
                        to="models_app.serverrack",
                        verbose_name="Стойка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Юнит",
                "verbose_name_plural": "Юниты",
                "db_table": "unit",
            },
            bases=(
                models.Model,
                models_app.models.mixins.show_model_info_mixin.ShowModelInfoMixin,
            ),
        ),
        migrations.CreateModel(
            name="Vlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("ip", models.GenericIPAddressField(verbose_name="IP адрес")),
                ("device_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "device_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "segment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="models_app.segment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vlan",
                "verbose_name_plural": "Vlan's",
                "db_table": "vlan",
            },
            bases=(
                models.Model,
                models_app.models.mixins.show_model_info_mixin.ShowModelInfoMixin,
            ),
        ),
    ]
