# Generated by Django 5.1.1 on 2024-12-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheme",
            name="title",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="serverrack",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
