# Generated by Django 5.1.1 on 2024-12-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0002_create_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="connections",
            field=models.ManyToManyField(blank=True, to="models_app.equipment"),
        ),
    ]
