# Generated by Django 5.1.1 on 2024-12-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0002_alter_scheme_title_alter_serverrack_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serverrack",
            name="title",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
