# Generated by Django 5.1.1 on 2024-12-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0002_create_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheme",
            name="count_build",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="scheme",
            name="count_user",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
