# Generated by Django 5.1.1 on 2024-12-26 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0002_create_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unit",
            name="equipment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="units",
                related_query_name="unit",
                to="models_app.equipment",
                verbose_name="Оборудование",
            ),
        ),
    ]
