# Generated by Django 5.1.3 on 2025-02-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0002_create_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipmenttemplate",
            name="model",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Модель"
            ),
        ),
    ]
