# Generated by Django 5.1.1 on 2024-12-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0003_alter_equipment_connections"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="floor",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
