# Generated by Django 5.1.3 on 2025-02-21 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0003_alter_equipmenttemplate_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vlan",
            name="segment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vlans",
                related_query_name="vlan",
                to="models_app.segment",
                verbose_name="vlan",
            ),
        ),
    ]
