# Generated by Django 5.1.1 on 2024-12-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0003_scheme_count_build_scheme_count_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheme",
            name="count_build",
            field=models.PositiveIntegerField(
                blank=True, default=0, verbose_name="Количество строений"
            ),
        ),
        migrations.AlterField(
            model_name="scheme",
            name="count_user",
            field=models.PositiveIntegerField(
                blank=True, default=0, verbose_name="Количество пользователей"
            ),
        ),
    ]
