# Generated by Django 5.1.1 on 2024-12-17 18:33

import django.contrib.postgres.fields
import django.db.models.deletion
import models_app.models.mixins.show_model_info_mixin
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0003_alter_serverrack_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="porttemplate",
            name="count",
        ),
        migrations.RemoveField(
            model_name="porttemplate",
            name="equipment_tmp",
        ),
        migrations.RemoveField(
            model_name="porttemplate",
            name="lines",
        ),
        migrations.RemoveField(
            model_name="porttemplate",
            name="unit",
        ),
        migrations.CreateModel(
            name="PortShip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("count", models.IntegerField()),
                (
                    "unit",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                        verbose_name="В каком юните расположен",
                    ),
                ),
                (
                    "lines",
                    models.IntegerField(
                        default=2, null=True, verbose_name="Количество занимаемых линий"
                    ),
                ),
                (
                    "equipment_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="models_app.equipmenttemplate",
                    ),
                ),
                (
                    "port_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="models_app.porttemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Промежуточная таблица портов",
                "verbose_name_plural": "Промежуточная таблица портов",
                "db_table": "port_ship",
                "unique_together": {("equipment_template", "port_template")},
            },
            bases=(
                models.Model,
                models_app.models.mixins.show_model_info_mixin.ShowModelInfoMixin,
            ),
        ),
        migrations.AddField(
            model_name="equipmenttemplate",
            name="port",
            field=models.ManyToManyField(
                through="models_app.PortShip", to="models_app.porttemplate"
            ),
        ),
    ]
