# Generated by Django 5.1.1 on 2024-12-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0004_remove_porttemplate_count_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="equipmenttemplatetype",
            options={
                "verbose_name": "Тип оборудования",
                "verbose_name_plural": "Типы оборудований",
            },
        ),
        migrations.AlterField(
            model_name="equipmenttemplatetype",
            name="is_active",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
