# Generated by Django 5.0.6 on 2024-06-03 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0004_alter_access_role_alter_equipmenttemplate_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="porttemplate",
            name="equipment_tmp",
            field=models.ManyToManyField(
                null=True,
                related_name="port_template",
                to="models_app.equipmenttemplate",
                verbose_name="Шаблон оборудования",
            ),
        ),
        migrations.AlterField(
            model_name="access",
            name="role",
            field=models.CharField(
                choices=[
                    ("Change", "Изменение"),
                    ("Creator", "Создатель"),
                    ("Read", "Чтение"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="port",
            name="line_type",
            field=models.CharField(
                choices=[
                    ("Ethernet", "Медный провод"),
                    ("None", "None"),
                    ("multi_mode", "Многомодовый"),
                    ("single-mode", "Одномодовый"),
                ],
                max_length=100,
                null=True,
                verbose_name="Тип линии",
            ),
        ),
        migrations.AlterField(
            model_name="speedtemplate",
            name="unit",
            field=models.CharField(
                choices=[("Kb", "Kb"), ("Gb", "Gb"), ("Mb", "Mb")],
                max_length=50,
                verbose_name="Единица измерения",
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="side",
            field=models.CharField(
                choices=[("Back", "Тыльная"), ("Front", "Лицевая")], max_length=100
            ),
        ),
    ]
