# Generated by Django 5.1.1 on 2024-12-29 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0004_room_floor"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="scheme",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="equipments",
                related_query_name="equipment",
                to="models_app.scheme",
            ),
            preserve_default=False,
        ),
    ]
