# Generated by Django 5.1.1 on 2024-12-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0004_alter_scheme_count_build_alter_scheme_count_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vlan",
            name="ip",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="IP адрес"
            ),
        ),
    ]
