# Generated by Django 5.1.3 on 2025-02-28 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0004_alter_vlan_segment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Figure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("x", models.FloatField()),
                ("y", models.FloatField()),
                ("width", models.IntegerField()),
                ("height", models.IntegerField()),
                (
                    "schemes",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_figure_schemes",
                        related_query_name="figure_scheme_map",
                        to="models_app.schememap",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фигура",
                "verbose_name_plural": "Фигуры",
                "db_table": "figure",
            },
        ),
    ]
