# Generated by Django 5.1.1 on 2024-12-18 23:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0005_alter_vlan_ip"),
    ]

    operations = [
        migrations.AddField(
            model_name="line",
            name="connection",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), blank=True, default=list, size=None
            ),
        ),
    ]
