# Generated by Django 5.1.3 on 2025-03-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0005_figure"),
    ]

    operations = [
        migrations.AddField(
            model_name="figure",
            name="type",
            field=models.FloatField(
                choices=[("Rectangle", "Прямоугольник")], default=1, max_length=255
            ),
            preserve_default=False,
        ),
    ]
