# Generated by Django 5.1.1 on 2024-12-17 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0005_alter_equipmenttemplatetype_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="speed",
            name="unit",
        ),
    ]
