# Generated by Django 5.1.1 on 2024-12-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0005_equipment_scheme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="floor",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
