# Generated by Django 5.0.6 on 2024-06-04 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0006_porttemplate_count_alter_access_role_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="access",
            name="role",
            field=models.CharField(
                choices=[
                    ("Read", "Чтение"),
                    ("Change", "Изменение"),
                    ("Creator", "Создатель"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="equipmenttemplate",
            name="type",
            field=models.CharField(
                choices=[
                    ("Passive", "Пассивное оборудование"),
                    ("Server", "Сервер"),
                    ("Switch", "Коммутатор"),
                ],
                max_length=100,
                verbose_name="Тип оборудования",
            ),
        ),
        migrations.AlterField(
            model_name="port",
            name="line_type",
            field=models.CharField(
                choices=[
                    ("Ethernet", "Медный провод"),
                    ("multi_mode", "Многомодовый"),
                    ("single-mode", "Одномодовый"),
                    ("None", "None"),
                ],
                max_length=100,
                null=True,
                verbose_name="Тип линии",
            ),
        ),
        migrations.AlterField(
            model_name="port",
            name="vlan_type",
            field=models.CharField(
                choices=[("Trunk", "Trunk"), ("None", "None"), ("Access", "Access")],
                max_length=100,
                null=True,
                verbose_name="Тип vlan",
            ),
        ),
        migrations.AlterField(
            model_name="porttemplate",
            name="equipment_tmp",
            field=models.ManyToManyField(
                related_name="port_template",
                to="models_app.equipmenttemplate",
                verbose_name="Шаблон оборудования",
            ),
        ),
        migrations.AlterField(
            model_name="speedtemplate",
            name="unit",
            field=models.CharField(
                choices=[("Gb", "Gb"), ("Kb", "Kb"), ("Mb", "Mb")],
                max_length=50,
                verbose_name="Единица измерения",
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="side",
            field=models.CharField(
                choices=[("Front", "Лицевая"), ("Back", "Тыльная")], max_length=100
            ),
        ),
    ]
