# Generated by Django 5.1.1 on 2025-01-04 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0006_alter_room_floor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="port",
            name="port_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ports",
                related_query_name="port",
                to="models_app.porttemplate",
                verbose_name="Шаблон порта",
            ),
        ),
    ]
