# Generated by Django 5.1.3 on 2025-03-02 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0006_figure_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="figure",
            name="type",
            field=models.CharField(
                choices=[("Rectangle", "Прямоугольник")], max_length=255
            ),
        ),
    ]
