# Generated by Django 5.1.1 on 2024-12-19 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0006_line_connection"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="connections",
            field=models.ManyToManyField(
                blank=True, null=True, to="models_app.equipment"
            ),
        ),
    ]
