# Generated by Django 5.1.1 on 2024-12-17 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0006_remove_speed_unit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="port",
            name="line_type",
        ),
        migrations.AddField(
            model_name="porttemplate",
            name="line_type",
            field=models.ManyToManyField(
                related_name="port_templates",
                related_query_name="port_template",
                to="models_app.linetype",
                verbose_name="Потдерживаемы типы лииний",
            ),
        ),
    ]
