# Generated by Django 5.1.1 on 2025-01-08 05:11

import django.contrib.postgres.fields
import django.db.models.deletion
import models_app.models.mixins.show_model_info_mixin
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0007_alter_port_port_template"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchemeMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheme_maps",
                        related_query_name="scheme_map",
                        to="models_app.scheme",
                    ),
                ),
            ],
            options={
                "db_table": "schemes",
            },
            bases=(
                models.Model,
                models_app.models.mixins.show_model_info_mixin.ShowModelInfoMixin,
            ),
        ),
        migrations.CreateModel(
            name="EquipmentSchemeIsPassive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("coord_x", models.IntegerField(blank=True, null=True)),
                ("coord_y", models.IntegerField(blank=True, null=True)),
                (
                    "connection_front",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), default=list, size=None
                    ),
                ),
                (
                    "connection_back",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), default=list, size=None
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_equipments_scheme",
                        related_query_name="equipment_scheme",
                        to="models_app.equipment",
                        verbose_name="Оборудование в схеме",
                    ),
                ),
                (
                    "schemes",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_equipment_schemes",
                        related_query_name="equipment_scheme_map",
                        to="models_app.schememap",
                    ),
                ),
            ],
            options={
                "db_table": "equipment_scheme_is_passive",
            },
            bases=(
                models.Model,
                models_app.models.mixins.show_model_info_mixin.ShowModelInfoMixin,
            ),
        ),
        migrations.CreateModel(
            name="EquipmentSchemeIsActive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("coord_x", models.IntegerField(blank=True, null=True)),
                ("coord_y", models.IntegerField(blank=True, null=True)),
                (
                    "connection_active",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), default=list, size=None
                    ),
                ),
                (
                    "connection_passive",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), default=list, size=None
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_equipments_scheme",
                        related_query_name="equipment_scheme",
                        to="models_app.equipment",
                        verbose_name="Оборудование в схеме",
                    ),
                ),
                (
                    "schemes",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_equipment_schemes",
                        related_query_name="equipment_scheme_map",
                        to="models_app.schememap",
                    ),
                ),
            ],
            options={
                "db_table": "equipment_scheme_is_active",
            },
            bases=(
                models.Model,
                models_app.models.mixins.show_model_info_mixin.ShowModelInfoMixin,
            ),
        ),
    ]
