# Generated by Django 5.2.7 on 2026-03-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0007_alter_figure_type"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="vlan",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="vlan",
            name="id_name",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="vlan",
            unique_together={("id_name", "segment")},
        ),
    ]
