# Generated by Django 5.0.6 on 2024-06-04 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0007_alter_access_role_alter_equipmenttemplate_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="access",
            name="role",
            field=models.CharField(
                choices=[
                    ("Read", "Чтение"),
                    ("Creator", "Создатель"),
                    ("Change", "Изменение"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="equipmenttemplate",
            name="manufacturer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="equpment_template",
                to="models_app.manufacturer",
                verbose_name="Производитель",
            ),
        ),
        migrations.AlterField(
            model_name="equipmenttemplate",
            name="type",
            field=models.CharField(
                choices=[
                    ("Switch", "Коммутатор"),
                    ("Passive", "Пассивное оборудование"),
                    ("Server", "Сервер"),
                ],
                max_length=100,
                verbose_name="Тип оборудования",
            ),
        ),
        migrations.AlterField(
            model_name="port",
            name="line_type",
            field=models.CharField(
                choices=[
                    ("None", "None"),
                    ("Ethernet", "Медный провод"),
                    ("multi_mode", "Многомодовый"),
                    ("single-mode", "Одномодовый"),
                ],
                max_length=100,
                null=True,
                verbose_name="Тип линии",
            ),
        ),
        migrations.AlterField(
            model_name="port",
            name="vlan_type",
            field=models.CharField(
                choices=[("Trunk", "Trunk"), ("Access", "Access"), ("None", "None")],
                max_length=100,
                null=True,
                verbose_name="Тип vlan",
            ),
        ),
        migrations.AlterField(
            model_name="speedtemplate",
            name="unit",
            field=models.CharField(
                choices=[("Mb", "Mb"), ("Gb", "Gb"), ("Kb", "Kb")],
                max_length=50,
                verbose_name="Единица измерения",
            ),
        ),
    ]
