# Generated by Django 5.1.1 on 2024-12-17 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0007_remove_port_line_type_porttemplate_line_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="equipment",
            name="room",
        ),
    ]
