# Generated by Django 5.1.1 on 2024-12-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0007_equipment_connections"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="equipments",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="related_equipments",
                to="models_app.equipment",
            ),
        ),
    ]
