# Generated by Django 5.1.1 on 2025-01-18 20:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0008_schememap_equipmentschemeispassive_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipmentschemeisactive",
            name="connection_active",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="equipmentschemeisactive",
            name="connection_passive",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="equipmentschemeispassive",
            name="connection_back",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="equipmentschemeispassive",
            name="connection_front",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
    ]
