# Generated by Django 5.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0008_alter_vlan_unique_together_vlan_id_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vlandevice",
            name="mask",
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name="Маска подсети"),
        ),
    ]
