# Generated by Django 5.0.6 on 2024-06-04 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0008_alter_access_role_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="access",
            name="role",
            field=models.CharField(
                choices=[
                    ("Creator", "Создатель"),
                    ("Change", "Изменение"),
                    ("Read", "Чтение"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="equipmenttemplate",
            name="type",
            field=models.CharField(
                choices=[
                    ("Passive", "Пассивное оборудование"),
                    ("Switch", "Коммутатор"),
                    ("Server", "Сервер"),
                ],
                max_length=100,
                verbose_name="Тип оборудования",
            ),
        ),
        migrations.AlterField(
            model_name="port",
            name="line_type",
            field=models.CharField(
                choices=[
                    ("Ethernet", "Медный провод"),
                    ("multi_mode", "Многомодовый"),
                    ("None", "None"),
                    ("single-mode", "Одномодовый"),
                ],
                max_length=100,
                null=True,
                verbose_name="Тип линии",
            ),
        ),
        migrations.AlterField(
            model_name="port",
            name="vlan_type",
            field=models.CharField(
                choices=[("Trunk", "Trunk"), ("None", "None"), ("Access", "Access")],
                max_length=100,
                null=True,
                verbose_name="Тип vlan",
            ),
        ),
        migrations.RemoveField(
            model_name="porttemplate",
            name="equipment_tmp",
        ),
        migrations.AlterField(
            model_name="room",
            name="type",
            field=models.CharField(
                choices=[("Server", "Серверная"), ("Regular", "Обычная")],
                max_length=100,
                verbose_name="Тип комнаты",
            ),
        ),
        migrations.AlterField(
            model_name="speedtemplate",
            name="unit",
            field=models.CharField(
                choices=[("Kb", "Kb"), ("Mb", "Mb"), ("Gb", "Gb")],
                max_length=50,
                verbose_name="Единица измерения",
            ),
        ),
        migrations.AddField(
            model_name="porttemplate",
            name="equipment_tmp",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="port_template",
                to="models_app.equipmenttemplate",
                verbose_name="Шаблон оборудования",
            ),
            preserve_default=False,
        ),
    ]
