# Generated by Django 5.1.1 on 2024-12-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0008_room_equipments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="equipments",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="rooms", to="models_app.equipment"
            ),
        ),
    ]
