# Generated by Django 5.1.1 on 2024-12-17 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0008_remove_equipment_room"),
    ]

    operations = [
        migrations.AddField(
            model_name="port",
            name="back_side",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="back",
                to="models_app.port",
            ),
        ),
        migrations.AddField(
            model_name="port",
            name="front_side",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="front",
                to="models_app.port",
            ),
        ),
    ]
