# Generated by Django 5.1.1 on 2025-01-18 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0009_alter_equipmentschemeisactive_connection_active_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="EquipmentSchemeIsPassive",
            new_name="EquipmentScheme",
        ),
        migrations.AlterModelTable(
            name="equipmentscheme",
            table="equipment_scheme",
        ),
        migrations.DeleteModel(
            name="EquipmentSchemeIsActive",
        ),
    ]
