# Generated by Django 5.1.1 on 2024-12-19 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0009_alter_room_equipments"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="equipments",
        ),
        migrations.AddField(
            model_name="equipment",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="equipments",
                related_query_name="equipmet",
                to="models_app.room",
                verbose_name="Расположение в комнате",
            ),
        ),
    ]
