# Generated by Django 5.1.1 on 2024-12-17 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0009_port_back_side_port_front_side"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="free_ports",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Количество свободных портов"
            ),
        ),
        migrations.AlterField(
            model_name="serverrack",
            name="free_power",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, verbose_name="Свободноя мощность"
            ),
        ),
        migrations.AlterField(
            model_name="serverrack",
            name="free_units",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Свободные юниты"
            ),
        ),
        migrations.AlterField(
            model_name="serverrack",
            name="max_power",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, verbose_name="Максимальная мощность"
            ),
        ),
        migrations.AlterField(
            model_name="speed",
            name="value",
            field=models.PositiveBigIntegerField(
                unique=True, verbose_name="Значение скорости"
            ),
        ),
    ]
