# Generated by Django 5.1.1 on 2024-12-17 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0010_alter_equipment_free_ports_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sfptemplate",
            name="line_type",
        ),
        migrations.AddField(
            model_name="sfptemplate",
            name="line_type",
            field=models.ManyToManyField(
                related_name="sfp_templates",
                related_query_name="sfp_template",
                to="models_app.linetype",
                verbose_name="Потдерживаемы типы лииний",
            ),
        ),
    ]
