# Generated by Django 5.1.1 on 2024-12-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0010_remove_room_equipments_equipment_room"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipmenttemplate",
            name="model",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Модель",
            ),
        ),
    ]
