# Generated by Django 5.1.1 on 2025-01-18 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0010_rename_equipmentschemeispassive_equipmentscheme_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="equipmentscheme",
            old_name="connection_back",
            new_name="connection_active",
        ),
        migrations.RenameField(
            model_name="equipmentscheme",
            old_name="connection_front",
            new_name="connection_passive",
        ),
    ]
