# Generated by Django 5.1.1 on 2024-12-24 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0011_alter_equipmenttemplate_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="line",
            name="filled_line",
        ),
    ]
