# Generated by Django 5.1.3 on 2025-01-29 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        (
            "models_app",
            "0011_rename_connection_back_equipmentscheme_connection_active_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="access",
            name="scheme",
        ),
        migrations.AddField(
            model_name="access",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="access",
            name="object_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
    ]
