# Generated by Django 5.1.3 on 2025-01-29 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("models_app", "0012_remove_access_scheme_access_object_id_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="access",
            unique_together={("user", "object_type", "object_id")},
        ),
    ]
