# Generated by Django 5.1.1 on 2025-02-03 07:40

import django.db.models.deletion
import models_app.models.mixins.show_model_info_mixin
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("models_app", "0013_alter_access_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vlan",
            name="device_id",
        ),
        migrations.RemoveField(
            model_name="vlan",
            name="device_type",
        ),
        migrations.RemoveField(
            model_name="vlan",
            name="ip",
        ),
        migrations.CreateModel(
            name="VlanDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP адрес"
                    ),
                ),
                ("device_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "device_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "vlan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="models_app.vlan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vlan Device",
                "verbose_name_plural": "Vlan device's",
                "db_table": "vlan_device",
            },
            bases=(
                models.Model,
                models_app.models.mixins.show_model_info_mixin.ShowModelInfoMixin,
            ),
        ),
    ]
