# Generated by Django 5.1.1 on 2025-02-03 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0014_remove_vlan_device_id_remove_vlan_device_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vlan",
            name="segment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_query_name="vlan",
                to="models_app.segment",
                verbose_name="vlan",
            ),
        ),
    ]
