# Generated by Django 5.0.6 on 2024-06-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0014_port_port_template_alter_access_role_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sfptemplate",
            name="port_template",
        ),
        migrations.AddField(
            model_name="sfptemplate",
            name="speed",
            field=models.IntegerField(default=2, verbose_name="Скорость"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sfptemplate",
            name="unit",
            field=models.CharField(
                choices=[("Gb", "Gb"), ("Kb", "Kb"), ("Mb", "Mb")],
                default=1,
                max_length=50,
                verbose_name="Единица измерения",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="access",
            name="role",
            field=models.CharField(
                choices=[
                    ("Creator", "Создатель"),
                    ("Change", "Изменение"),
                    ("Read", "Чтение"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="equipmenttemplate",
            name="type",
            field=models.CharField(
                choices=[
                    ("Server", "Сервер"),
                    ("Switch", "Коммутатор"),
                    ("Passive", "Пассивное оборудование"),
                ],
                max_length=100,
                verbose_name="Тип оборудования",
            ),
        ),
        migrations.AlterField(
            model_name="port",
            name="line_type",
            field=models.CharField(
                choices=[
                    ("multi_mode", "Многомодовый"),
                    ("single-mode", "Одномодовый"),
                    ("None", "None"),
                    ("Ethernet", "Медный провод"),
                ],
                max_length=100,
                null=True,
                verbose_name="Тип линии",
            ),
        ),
        migrations.AlterField(
            model_name="port",
            name="vlan_type",
            field=models.CharField(
                choices=[("Access", "Access"), ("Trunk", "Trunk"), ("None", "None")],
                max_length=100,
                null=True,
                verbose_name="Тип vlan",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="type",
            field=models.CharField(
                choices=[("Server", "Серверная"), ("Regular", "Обычная")],
                max_length=100,
                verbose_name="Тип комнаты",
            ),
        ),
        migrations.AlterField(
            model_name="speedtemplate",
            name="unit",
            field=models.CharField(
                choices=[("Gb", "Gb"), ("Kb", "Kb"), ("Mb", "Mb")],
                max_length=50,
                verbose_name="Единица измерения",
            ),
        ),
    ]
