# Generated by Django 5.0.6 on 2024-06-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "models_app",
            "0015_remove_sfptemplate_port_template_sfptemplate_speed_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sfptemplate",
            name="unit",
        ),
        migrations.RemoveField(
            model_name="speedtemplate",
            name="unit",
        ),
        migrations.AlterField(
            model_name="access",
            name="role",
            field=models.CharField(
                choices=[
                    ("Read", "Чтение"),
                    ("Change", "Изменение"),
                    ("Creator", "Создатель"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="equipmenttemplate",
            name="type",
            field=models.CharField(
                choices=[
                    ("Switch", "Коммутатор"),
                    ("Passive", "Пассивное оборудование"),
                    ("Server", "Сервер"),
                ],
                max_length=100,
                verbose_name="Тип оборудования",
            ),
        ),
        migrations.AlterField(
            model_name="port",
            name="vlan_type",
            field=models.CharField(
                choices=[("Access", "Access"), ("None", "None"), ("Trunk", "Trunk")],
                max_length=100,
                null=True,
                verbose_name="Тип vlan",
            ),
        ),
    ]
