# Generated by Django 5.1.3 on 2025-02-03 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0015_alter_vlan_segment"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="vlan",
            unique_together={("name", "segment")},
        ),
    ]
