# Generated by Django 5.1.3 on 2025-02-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("models_app", "0016_alter_vlan_unique_together"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="vlandevice",
            constraint=models.UniqueConstraint(
                fields=("device_type", "device_id", "vlan"), name="unique_device_vlan"
            ),
        ),
    ]
