# Generated by Django 5.1.3 on 2025-02-05 18:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0017_vlandevice_unique_device_vlan"),
    ]

    operations = [
        migrations.AddField(
            model_name="portmode",
            name="alfa",
            field=models.FloatField(
                default=0, validators=[django.core.validators.MaxValueValidator(1)]
            ),
        ),
        migrations.AddField(
            model_name="portmode",
            name="blue",
            field=models.PositiveIntegerField(
                default=0, validators=[django.core.validators.MaxValueValidator(255)]
            ),
        ),
        migrations.AddField(
            model_name="portmode",
            name="green",
            field=models.PositiveIntegerField(
                default=0, validators=[django.core.validators.MaxValueValidator(255)]
            ),
        ),
        migrations.AddField(
            model_name="portmode",
            name="red",
            field=models.PositiveIntegerField(
                default=0, validators=[django.core.validators.MaxValueValidator(255)]
            ),
        ),
    ]
