# Generated by Django 5.1.3 on 2025-02-05 18:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0018_portmode_alfa_portmode_blue_portmode_green_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portmode",
            name="alfa",
            field=models.FloatField(
                blank=True,
                default=0,
                validators=[django.core.validators.MaxValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="portmode",
            name="blue",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                validators=[django.core.validators.MaxValueValidator(255)],
            ),
        ),
        migrations.AlterField(
            model_name="portmode",
            name="green",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                validators=[django.core.validators.MaxValueValidator(255)],
            ),
        ),
        migrations.AlterField(
            model_name="portmode",
            name="is_only_one_vlan",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="portmode",
            name="red",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                validators=[django.core.validators.MaxValueValidator(255)],
            ),
        ),
    ]
