# Generated by Django 5.1.3 on 2025-02-12 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0019_alter_portmode_alfa_alter_portmode_blue_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vlandevice",
            name="vlan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="devices",
                related_query_name="device",
                to="models_app.vlan",
            ),
        ),
    ]
