# Generated by Django 5.1.1 on 2025-02-15 17:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0020_alter_vlandevice_vlan"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="connection",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                blank=True,
                default=list,
                size=None,
                verbose_name="Подключенные строения",
            ),
        ),
    ]
