# Generated by Django 5.0.6 on 2024-06-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0020_equipment_free_ports_alter_access_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sfptemplate",
            name="name",
            field=models.CharField(default=1, verbose_name="Наименование sfp"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="access",
            name="role",
            field=models.CharField(
                choices=[
                    ("Change", "Изменение"),
                    ("Read", "Чтение"),
                    ("Creator", "Создатель"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="port",
            name="line_type",
            field=models.CharField(
                choices=[
                    ("multi_mode", "Многомодовый"),
                    ("Ethernet", "Медный провод"),
                    ("None", "None"),
                    ("single-mode", "Одномодовый"),
                ],
                max_length=100,
                null=True,
                verbose_name="Тип линии",
            ),
        ),
        migrations.AlterField(
            model_name="port",
            name="vlan_type",
            field=models.CharField(
                choices=[("None", "None"), ("Trunk", "Trunk"), ("Access", "Access")],
                max_length=100,
                null=True,
                verbose_name="Тип vlan",
            ),
        ),
    ]
