# Generated by Django 5.0.6 on 2024-06-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0023_sfptemplate_line_type_alter_access_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="vlan_ip",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Список vlan и принадлежащим им ip"
            ),
        ),
        migrations.AlterField(
            model_name="access",
            name="role",
            field=models.CharField(
                choices=[
                    ("Read", "Чтение"),
                    ("Change", "Изменение"),
                    ("Creator", "Создатель"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="equipmenttemplate",
            name="type",
            field=models.CharField(
                choices=[
                    ("Switch", "Коммутатор"),
                    ("Passive", "Пассивное оборудование"),
                    ("Server", "Сервер"),
                ],
                max_length=100,
                verbose_name="Тип оборудования",
            ),
        ),
        migrations.AlterField(
            model_name="port",
            name="line_type",
            field=models.CharField(
                choices=[
                    ("Ethernet", "Медный провод"),
                    ("multi_mode", "Многомодовый"),
                    ("None", "None"),
                    ("single-mode", "Одномодовый"),
                ],
                max_length=100,
                null=True,
                verbose_name="Тип линии",
            ),
        ),
        migrations.AlterField(
            model_name="port",
            name="vlan_type",
            field=models.CharField(
                choices=[("Access", "Access"), ("Trunk", "Trunk"), ("None", "None")],
                max_length=100,
                null=True,
                verbose_name="Тип vlan",
            ),
        ),
        migrations.AlterField(
            model_name="sfptemplate",
            name="line_type",
            field=models.CharField(
                choices=[
                    ("Ethernet", "Медный провод"),
                    ("multi_mode", "Многомодовый"),
                    ("None", "None"),
                    ("single-mode", "Одномодовый"),
                ],
                max_length=100,
                null=True,
                verbose_name="Тип линии",
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="side",
            field=models.CharField(
                choices=[("Back", "Тыльная"), ("Front", "Лицевая")], max_length=100
            ),
        ),
    ]
