# Generated by Django 5.0.6 on 2024-06-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0024_equipment_vlan_ip_alter_access_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="porttemplate",
            name="need_sfp",
            field=models.BooleanField(
                default=False, verbose_name="Необходимость sfp модуля"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="access",
            name="role",
            field=models.CharField(
                choices=[
                    ("Read", "Чтение"),
                    ("Creator", "Создатель"),
                    ("Change", "Изменение"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="equipmenttemplate",
            name="type",
            field=models.CharField(
                choices=[
                    ("Server", "Сервер"),
                    ("Switch", "Коммутатор"),
                    ("Passive", "Пассивное оборудование"),
                ],
                max_length=100,
                verbose_name="Тип оборудования",
            ),
        ),
        migrations.AlterField(
            model_name="port",
            name="line_type",
            field=models.CharField(
                choices=[
                    ("multi_mode", "Многомодовый"),
                    ("single-mode", "Одномодовый"),
                    ("Ethernet", "Медный провод"),
                    ("None", "None"),
                ],
                max_length=100,
                null=True,
                verbose_name="Тип линии",
            ),
        ),
        migrations.AlterField(
            model_name="port",
            name="vlan_type",
            field=models.CharField(
                choices=[("None", "None"), ("Trunk", "Trunk"), ("Access", "Access")],
                max_length=100,
                null=True,
                verbose_name="Тип vlan",
            ),
        ),
        migrations.AlterField(
            model_name="sfptemplate",
            name="line_type",
            field=models.CharField(
                choices=[
                    ("multi_mode", "Многомодовый"),
                    ("single-mode", "Одномодовый"),
                    ("Ethernet", "Медный провод"),
                    ("None", "None"),
                ],
                max_length=100,
                null=True,
                verbose_name="Тип линии",
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="side",
            field=models.CharField(
                choices=[("Front", "Лицевая"), ("Back", "Тыльная")], max_length=100
            ),
        ),
    ]
