# Generated by Django 5.0.6 on 2024-06-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0026_remove_porttemplate_need_sfp_alter_access_role_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="port",
            name="sfp",
        ),
        migrations.AlterField(
            model_name="access",
            name="role",
            field=models.CharField(
                choices=[
                    ("Creator", "Создатель"),
                    ("Read", "Чтение"),
                    ("Change", "Изменение"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="port",
            name="line_type",
            field=models.CharField(
                choices=[
                    ("None", "None"),
                    ("multi_mode", "Многомодовый"),
                    ("single-mode", "Одномодовый"),
                    ("Ethernet", "Медный провод"),
                ],
                max_length=100,
                null=True,
                verbose_name="Тип линии",
            ),
        ),
        migrations.AlterField(
            model_name="port",
            name="vlan_type",
            field=models.CharField(
                choices=[("None", "None"), ("Trunk", "Trunk"), ("Access", "Access")],
                max_length=100,
                null=True,
                verbose_name="Тип vlan",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="type",
            field=models.CharField(
                choices=[("Server", "Серверная"), ("Regular", "Обычная")],
                max_length=100,
                verbose_name="Тип комнаты",
            ),
        ),
        migrations.DeleteModel(
            name="SfpTemplate",
        ),
    ]
