# Generated by Django 5.0.6 on 2024-07-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0031_alter_access_role_alter_equipmenttemplate_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="serverrack",
            name="free_power",
            field=models.IntegerField(null=True, verbose_name="Свободноя мощность"),
        ),
        migrations.AddField(
            model_name="serverrack",
            name="free_units",
            field=models.IntegerField(null=True, verbose_name="Свободные юниты"),
        ),
        migrations.AlterField(
            model_name="access",
            name="role",
            field=models.CharField(
                choices=[
                    ("Creator", "Создатель"),
                    ("Change", "Изменение"),
                    ("Read", "Чтение"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="port",
            name="line_type",
            field=models.CharField(
                choices=[
                    ("single-mode", "Одномодовый"),
                    ("None", "None"),
                    ("multi_mode", "Многомодовый"),
                    ("Ethernet", "Медный провод"),
                ],
                max_length=100,
                null=True,
                verbose_name="Тип линии",
            ),
        ),
        migrations.AlterField(
            model_name="port",
            name="vlan_type",
            field=models.CharField(
                choices=[("None", "None"), ("Trunk", "Trunk"), ("Access", "Access")],
                max_length=100,
                null=True,
                verbose_name="Тип vlan",
            ),
        ),
        migrations.AlterField(
            model_name="serverrack",
            name="max_power",
            field=models.IntegerField(null=True, verbose_name="Максимальная мощность"),
        ),
    ]
