# Generated by Django 5.0.6 on 2024-07-01 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0033_alter_access_role_alter_equipmenttemplate_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="access",
            name="role",
            field=models.CharField(
                choices=[
                    ("Change", "Изменение"),
                    ("Read", "Чтение"),
                    ("Creator", "Создатель"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="equipmenttemplate",
            name="type",
            field=models.CharField(
                choices=[
                    ("Server", "Сервер"),
                    ("Passive", "Пассивное оборудование"),
                    ("Switch", "Коммутатор"),
                ],
                max_length=100,
                verbose_name="Тип оборудования",
            ),
        ),
        migrations.AlterField(
            model_name="port",
            name="line_type",
            field=models.CharField(
                choices=[
                    ("None", "None"),
                    ("Ethernet", "Медный провод"),
                    ("single-mode", "Одномодовый"),
                    ("multi_mode", "Многомодовый"),
                ],
                max_length=100,
                null=True,
                verbose_name="Тип линии",
            ),
        ),
        migrations.AlterField(
            model_name="port",
            name="vlan_type",
            field=models.CharField(
                choices=[("Access", "Access"), ("None", "None"), ("Trunk", "Trunk")],
                max_length=100,
                null=True,
                verbose_name="Тип vlan",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="type",
            field=models.CharField(
                choices=[("Regular", "Обычная"), ("Server", "Серверная")],
                max_length=100,
                verbose_name="Тип комнаты",
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="equipment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="unit",
                to="models_app.equipment",
                verbose_name="Оборудование",
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="side",
            field=models.CharField(
                choices=[("Back", "Тыльная"), ("Front", "Лицевая")], max_length=100
            ),
        ),
    ]
