# Generated by Django 5.0.6 on 2024-07-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0035_port_connection_pigtail_alter_access_role_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipmenttemplate",
            name="power",
            field=models.IntegerField(null=True, verbose_name="Мощность"),
        ),
        migrations.AlterField(
            model_name="equipmenttemplate",
            name="type",
            field=models.CharField(
                choices=[
                    ("Switch", "Коммутатор"),
                    ("Passive", "Пассивное оборудование"),
                    ("Server", "Сервер"),
                ],
                max_length=100,
                verbose_name="Тип оборудования",
            ),
        ),
        migrations.AlterField(
            model_name="port",
            name="line_type",
            field=models.CharField(
                choices=[
                    ("None", "None"),
                    ("single-mode", "Одномодовый"),
                    ("Ethernet", "Медный провод"),
                    ("multi_mode", "Многомодовый"),
                ],
                max_length=100,
                null=True,
                verbose_name="Тип линии",
            ),
        ),
        migrations.AlterField(
            model_name="port",
            name="vlan_type",
            field=models.CharField(
                choices=[("None", "None"), ("Access", "Access"), ("Trunk", "Trunk")],
                max_length=100,
                null=True,
                verbose_name="Тип vlan",
            ),
        ),
    ]
