# Generated by Django 5.0.6 on 2024-07-05 18:47

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0036_alter_equipmenttemplate_power_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TypePort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Наименование")),
            ],
        ),
        migrations.AlterField(
            model_name="access",
            name="role",
            field=models.CharField(
                choices=[
                    ("Creator", "Создатель"),
                    ("Change", "Изменение"),
                    ("Read", "Чтение"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="equipmenttemplate",
            name="type",
            field=models.CharField(
                choices=[
                    ("Passive", "Пассивное оборудование"),
                    ("Server", "Сервер"),
                    ("Switch", "Коммутатор"),
                ],
                max_length=100,
                verbose_name="Тип оборудования",
            ),
        ),
        migrations.AlterField(
            model_name="port",
            name="line_type",
            field=models.CharField(
                choices=[
                    ("None", "None"),
                    ("multi_mode", "Многомодовый"),
                    ("single-mode", "Одномодовый"),
                    ("Ethernet", "Медный провод"),
                ],
                max_length=100,
                null=True,
                verbose_name="Тип линии",
            ),
        ),
        migrations.AlterField(
            model_name="port",
            name="vlan_type",
            field=models.CharField(
                choices=[("Trunk", "Trunk"), ("None", "None"), ("Access", "Access")],
                max_length=100,
                null=True,
                verbose_name="Тип vlan",
            ),
        ),
        migrations.CreateModel(
            name="SfpTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, null=True, verbose_name="Наименование"
                    ),
                ),
                (
                    "speed",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Поддерживаемые скорости",
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sfp_template",
                        to="models_app.manufacturer",
                        verbose_name="Произваодитель",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sfp_template",
                        to="models_app.typeport",
                        verbose_name="Тип порта",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="port",
            name="sfp",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="port",
                to="models_app.sfptemplate",
                verbose_name="Sfp",
            ),
        ),
        migrations.AddField(
            model_name="porttemplate",
            name="type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="port_template",
                to="models_app.typeport",
                verbose_name="Тип порта",
            ),
            preserve_default=False,
        ),
    ]
