# Generated by Django 5.0.6 on 2024-07-05 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0038_porttemplate_modular_alter_access_role_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="porttemplate",
            old_name="type",
            new_name="type_port",
        ),
        migrations.RenameField(
            model_name="sfptemplate",
            old_name="type",
            new_name="type_port",
        ),
        migrations.AlterField(
            model_name="access",
            name="role",
            field=models.CharField(
                choices=[
                    ("Creator", "Создатель"),
                    ("Change", "Изменение"),
                    ("Read", "Чтение"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="port",
            name="line_type",
            field=models.CharField(
                choices=[
                    ("single-mode", "Одномодовый"),
                    ("None", "None"),
                    ("multi_mode", "Многомодовый"),
                    ("Ethernet", "Медный провод"),
                ],
                max_length=100,
                null=True,
                verbose_name="Тип линии",
            ),
        ),
        migrations.AlterField(
            model_name="port",
            name="vlan_type",
            field=models.CharField(
                choices=[("Access", "Access"), ("None", "None"), ("Trunk", "Trunk")],
                max_length=100,
                null=True,
                verbose_name="Тип vlan",
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="side",
            field=models.CharField(
                choices=[("Front", "Лицевая"), ("Back", "Тыльная")], max_length=100
            ),
        ),
    ]
