# Generated by Django 5.0.6 on 2024-07-05 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0039_rename_type_porttemplate_type_port_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sfptemplate",
            name="line_type",
            field=models.CharField(
                choices=[
                    ("single-mode", "Одномодовый"),
                    ("multi_mode", "Многомодовый"),
                    ("Ethernet", "Медный провод"),
                    ("None", "None"),
                ],
                default=1,
                verbose_name="Тип линии",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="access",
            name="role",
            field=models.CharField(
                choices=[
                    ("Read", "Чтение"),
                    ("Creator", "Создатель"),
                    ("Change", "Изменение"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="port",
            name="line_type",
            field=models.CharField(
                choices=[
                    ("single-mode", "Одномодовый"),
                    ("multi_mode", "Многомодовый"),
                    ("Ethernet", "Медный провод"),
                    ("None", "None"),
                ],
                max_length=100,
                null=True,
                verbose_name="Тип линии",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="type",
            field=models.CharField(
                choices=[("Server", "Серверная"), ("Regular", "Обычная")],
                max_length=100,
                verbose_name="Тип комнаты",
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="side",
            field=models.CharField(
                choices=[("Back", "Тыльная"), ("Front", "Лицевая")], max_length=100
            ),
        ),
    ]
