# Generated by Django 5.0.6 on 2024-07-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0040_sfptemplate_line_type_alter_access_role_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="access",
            name="role",
            field=models.CharField(
                choices=[
                    ("Creator", "Создатель"),
                    ("Change", "Изменение"),
                    ("Read", "Чтение"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="equipmenttemplate",
            name="type",
            field=models.CharField(
                choices=[
                    ("Passive", "Пассивное оборудование"),
                    ("Server", "Сервер"),
                    ("Switch", "Коммутатор"),
                ],
                max_length=100,
                verbose_name="Тип оборудования",
            ),
        ),
        migrations.AlterField(
            model_name="port",
            name="line_type",
            field=models.CharField(
                choices=[
                    ("multi_mode", "Многомодовый"),
                    ("Ethernet", "Медный провод"),
                    ("single-mode", "Одномодовый"),
                    ("None", "None"),
                ],
                max_length=100,
                null=True,
                verbose_name="Тип линии",
            ),
        ),
        migrations.AlterField(
            model_name="port",
            name="vlan_type",
            field=models.CharField(
                choices=[("Access", "Access"), ("Trunk", "Trunk"), ("None", "None")],
                max_length=100,
                null=True,
                verbose_name="Тип vlan",
            ),
        ),
        migrations.AlterField(
            model_name="sfptemplate",
            name="line_type",
            field=models.CharField(
                choices=[
                    ("multi_mode", "Многомодовый"),
                    ("None", "None"),
                    ("single-mode", "Одномодовый"),
                    ("Ethernet", "Медный провод"),
                ],
                verbose_name="Тип линии",
            ),
        ),
        migrations.AlterField(
            model_name="sfptemplate",
            name="name",
            field=models.CharField(
                max_length=150, null=True, unique=True, verbose_name="Наименование"
            ),
        ),
        migrations.AlterField(
            model_name="typeport",
            name="name",
            field=models.CharField(
                max_length=150, unique=True, verbose_name="Наименование"
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="side",
            field=models.CharField(
                choices=[("Front", "Лицевая"), ("Back", "Тыльная")], max_length=100
            ),
        ),
    ]
