# Generated by Django 5.0.6 on 2024-07-09 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0041_alter_access_role_alter_equipmenttemplate_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="access",
            name="role",
            field=models.CharField(
                choices=[
                    ("Change", "Изменение"),
                    ("Read", "Чтение"),
                    ("Creator", "Создатель"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="equipmenttemplate",
            name="type",
            field=models.CharField(
                choices=[
                    ("Server", "Сервер"),
                    ("Switch", "Коммутатор"),
                    ("Passive", "Пассивное оборудование"),
                ],
                max_length=100,
                verbose_name="Тип оборудования",
            ),
        ),
        migrations.AlterField(
            model_name="port",
            name="line_type",
            field=models.CharField(
                choices=[
                    ("single-mode", "Одномодовый"),
                    ("multi_mode", "Многомодовый"),
                    ("None", "None"),
                    ("Ethernet", "Медный провод"),
                ],
                max_length=100,
                null=True,
                verbose_name="Тип линии",
            ),
        ),
        migrations.AlterField(
            model_name="port",
            name="vlan_type",
            field=models.CharField(
                choices=[("Trunk", "Trunk"), ("None", "None"), ("Access", "Access")],
                max_length=100,
                null=True,
                verbose_name="Тип vlan",
            ),
        ),
        migrations.AlterField(
            model_name="serverrack",
            name="free_power",
            field=models.IntegerField(
                default=models.IntegerField(
                    null=True, verbose_name="Максимальная мощность"
                ),
                null=True,
                verbose_name="Свободноя мощность",
            ),
        ),
        migrations.AlterField(
            model_name="serverrack",
            name="free_units",
            field=models.IntegerField(
                default=models.IntegerField(verbose_name="Количетсво юнитов"),
                null=True,
                verbose_name="Свободные юниты",
            ),
        ),
        migrations.AlterField(
            model_name="sfptemplate",
            name="line_type",
            field=models.CharField(
                choices=[
                    ("single-mode", "Одномодовый"),
                    ("multi_mode", "Многомодовый"),
                    ("None", "None"),
                    ("Ethernet", "Медный провод"),
                ],
                verbose_name="Тип линии",
            ),
        ),
    ]
