# Generated by Django 5.0.7 on 2024-07-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0048_alter_access_role_alter_equipmenttemplate_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="typeport",
            options={
                "verbose_name": "Тип портов",
                "verbose_name_plural": "Типы портов",
            },
        ),
        migrations.AddField(
            model_name="equipment",
            name="count_port",
            field=models.IntegerField(default=2, verbose_name="Количество портов"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="access",
            name="role",
            field=models.CharField(
                choices=[
                    ("Change", "Изменение"),
                    ("Read", "Чтение"),
                    ("Creator", "Создатель"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="equipmenttemplate",
            name="type",
            field=models.CharField(
                choices=[
                    ("Passive", "Пассивное оборудование"),
                    ("Server", "Сервер"),
                    ("Switch", "Коммутатор"),
                ],
                max_length=100,
                verbose_name="Тип оборудования",
            ),
        ),
        migrations.AlterField(
            model_name="port",
            name="line_type",
            field=models.CharField(
                choices=[
                    ("Ethernet", "Медный провод"),
                    ("single-mode", "Одномодовый"),
                    ("multi_mode", "Многомодовый"),
                    ("None", "None"),
                ],
                max_length=100,
                null=True,
                verbose_name="Тип линии",
            ),
        ),
        migrations.AlterField(
            model_name="sfptemplate",
            name="line_type",
            field=models.CharField(
                choices=[
                    ("Ethernet", "Медный провод"),
                    ("single-mode", "Одномодовый"),
                    ("multi_mode", "Многомодовый"),
                    ("None", "None"),
                ],
                verbose_name="Тип линии",
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="side",
            field=models.CharField(
                choices=[("Back", "Тыльная"), ("Front", "Лицевая")], max_length=100
            ),
        ),
    ]
