# Generated by Django 5.0.7 on 2024-07-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0049_alter_typeport_options_equipment_count_port_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="port_template_dict",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="access",
            name="role",
            field=models.CharField(
                choices=[
                    ("Creator", "Создатель"),
                    ("Change", "Изменение"),
                    ("Read", "Чтение"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="equipmenttemplate",
            name="type",
            field=models.CharField(
                choices=[
                    ("Server", "Сервер"),
                    ("Switch", "Коммутатор"),
                    ("Passive", "Пассивное оборудование"),
                ],
                max_length=100,
                verbose_name="Тип оборудования",
            ),
        ),
        migrations.AlterField(
            model_name="port",
            name="line_type",
            field=models.CharField(
                choices=[
                    ("single-mode", "Одномодовый"),
                    ("None", "None"),
                    ("Ethernet", "Медный провод"),
                    ("multi_mode", "Многомодовый"),
                ],
                max_length=100,
                null=True,
                verbose_name="Тип линии",
            ),
        ),
        migrations.AlterField(
            model_name="port",
            name="vlan_type",
            field=models.CharField(
                choices=[("Access", "Access"), ("None", "None"), ("Trunk", "Trunk")],
                max_length=100,
                null=True,
                verbose_name="Тип vlan",
            ),
        ),
        migrations.AlterField(
            model_name="sfptemplate",
            name="line_type",
            field=models.CharField(
                choices=[
                    ("single-mode", "Одномодовый"),
                    ("multi_mode", "Многомодовый"),
                    ("None", "None"),
                    ("Ethernet", "Медный провод"),
                ],
                verbose_name="Тип линии",
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="side",
            field=models.CharField(
                choices=[("Front", "Лицевая"), ("Back", "Тыльная")], max_length=100
            ),
        ),
    ]
