# Generated by Django 5.0.7 on 2024-07-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0050_equipment_port_template_dict_alter_access_role_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="port_template_dict",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="equipmenttemplate",
            name="type",
            field=models.CharField(
                choices=[
                    ("Switch", "Коммутатор"),
                    ("Server", "Сервер"),
                    ("Passive", "Пассивное оборудование"),
                ],
                max_length=100,
                verbose_name="Тип оборудования",
            ),
        ),
        migrations.AlterField(
            model_name="port",
            name="line_type",
            field=models.CharField(
                choices=[
                    ("Ethernet", "Медный провод"),
                    ("single-mode", "Одномодовый"),
                    ("None", "None"),
                    ("multi_mode", "Многомодовый"),
                ],
                max_length=100,
                null=True,
                verbose_name="Тип линии",
            ),
        ),
        migrations.AlterField(
            model_name="port",
            name="vlan_type",
            field=models.CharField(
                choices=[("Trunk", "Trunk"), ("None", "None"), ("Access", "Access")],
                max_length=100,
                null=True,
                verbose_name="Тип vlan",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="type",
            field=models.CharField(
                choices=[("Regular", "Обычная"), ("Server", "Серверная")],
                max_length=100,
                verbose_name="Тип комнаты",
            ),
        ),
        migrations.AlterField(
            model_name="sfptemplate",
            name="line_type",
            field=models.CharField(
                choices=[
                    ("Ethernet", "Медный провод"),
                    ("single-mode", "Одномодовый"),
                    ("None", "None"),
                    ("multi_mode", "Многомодовый"),
                ],
                verbose_name="Тип линии",
            ),
        ),
    ]
