# Generated by Django 5.0.7 on 2024-07-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0051_alter_equipment_port_template_dict_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="equipment",
            old_name="port_template_dict",
            new_name="count_port_template_dict",
        ),
        migrations.AlterField(
            model_name="access",
            name="role",
            field=models.CharField(
                choices=[
                    ("Read", "Чтение"),
                    ("Change", "Изменение"),
                    ("Creator", "Создатель"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="equipmenttemplate",
            name="type",
            field=models.CharField(
                choices=[
                    ("Server", "Сервер"),
                    ("Switch", "Коммутатор"),
                    ("Passive", "Пассивное оборудование"),
                ],
                max_length=100,
                verbose_name="Тип оборудования",
            ),
        ),
        migrations.AlterField(
            model_name="port",
            name="line_type",
            field=models.CharField(
                choices=[
                    ("single-mode", "Одномодовый"),
                    ("Ethernet", "Медный провод"),
                    ("multi_mode", "Многомодовый"),
                    ("None", "None"),
                ],
                max_length=100,
                null=True,
                verbose_name="Тип линии",
            ),
        ),
        migrations.AlterField(
            model_name="port",
            name="vlan_type",
            field=models.CharField(
                choices=[("Access", "Access"), ("None", "None"), ("Trunk", "Trunk")],
                max_length=100,
                null=True,
                verbose_name="Тип vlan",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="type",
            field=models.CharField(
                choices=[("Server", "Серверная"), ("Regular", "Обычная")],
                max_length=100,
                verbose_name="Тип комнаты",
            ),
        ),
        migrations.AlterField(
            model_name="sfptemplate",
            name="line_type",
            field=models.CharField(
                choices=[
                    ("single-mode", "Одномодовый"),
                    ("Ethernet", "Медный провод"),
                    ("multi_mode", "Многомодовый"),
                    ("None", "None"),
                ],
                verbose_name="Тип линии",
            ),
        ),
    ]
