# Generated by Django 5.0.7 on 2024-07-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "models_app",
            "0052_rename_port_template_dict_equipment_count_port_template_dict_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="access",
            name="role",
            field=models.CharField(
                choices=[
                    ("Change", "Изменение"),
                    ("Creator", "Создатель"),
                    ("Read", "Чтение"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="equipmenttemplate",
            name="model",
            field=models.CharField(max_length=100, unique=True, verbose_name="Модель"),
        ),
        migrations.AlterField(
            model_name="equipmenttemplate",
            name="type",
            field=models.CharField(
                choices=[
                    ("Switch", "Коммутатор"),
                    ("Server", "Сервер"),
                    ("Passive", "Пассивное оборудование"),
                ],
                max_length=100,
                verbose_name="Тип оборудования",
            ),
        ),
        migrations.AlterField(
            model_name="port",
            name="line_type",
            field=models.CharField(
                choices=[
                    ("None", "None"),
                    ("Ethernet", "Медный провод"),
                    ("single-mode", "Одномодовый"),
                    ("multi_mode", "Многомодовый"),
                ],
                max_length=100,
                null=True,
                verbose_name="Тип линии",
            ),
        ),
        migrations.AlterField(
            model_name="port",
            name="vlan_type",
            field=models.CharField(
                choices=[("Access", "Access"), ("Trunk", "Trunk"), ("None", "None")],
                max_length=100,
                null=True,
                verbose_name="Тип vlan",
            ),
        ),
        migrations.AlterField(
            model_name="sfptemplate",
            name="line_type",
            field=models.CharField(
                choices=[
                    ("multi_mode", "Многомодовый"),
                    ("Ethernet", "Медный провод"),
                    ("single-mode", "Одномодовый"),
                    ("None", "None"),
                ],
                verbose_name="Тип линии",
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="side",
            field=models.CharField(
                choices=[("Back", "Тыльная"), ("Front", "Лицевая")], max_length=100
            ),
        ),
    ]
