# Generated by Django 5.0.7 on 2024-08-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0054_equipmenttemplate_count_port_alter_access_role_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="access",
            name="role",
            field=models.CharField(
                choices=[
                    ("Read", "Чтение"),
                    ("Change", "Изменение"),
                    ("Creator", "Создатель"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="equipmenttemplate",
            name="type",
            field=models.CharField(
                choices=[
                    ("Switch", "Коммутатор"),
                    ("Passive", "Пассивное оборудование"),
                    ("Server", "Сервер"),
                ],
                max_length=100,
                verbose_name="Тип оборудования",
            ),
        ),
        migrations.AlterField(
            model_name="port",
            name="line_type",
            field=models.CharField(
                choices=[
                    ("None", "None"),
                    ("single-mode", "Одномодовый"),
                    ("multi_mode", "Многомодовый"),
                    ("Ethernet", "Медный провод"),
                ],
                max_length=100,
                null=True,
                verbose_name="Тип линии",
            ),
        ),
        migrations.AlterField(
            model_name="port",
            name="vlan_type",
            field=models.CharField(
                choices=[("None", "None"), ("Trunk", "Trunk"), ("Access", "Access")],
                max_length=100,
                null=True,
                verbose_name="Тип vlan",
            ),
        ),
        migrations.AlterField(
            model_name="porttemplate",
            name="name",
            field=models.CharField(
                max_length=150, null=True, verbose_name="Наименование"
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="type",
            field=models.CharField(
                choices=[("Server", "Серверная"), ("Regular", "Обычная")],
                max_length=100,
                verbose_name="Тип комнаты",
            ),
        ),
        migrations.AlterField(
            model_name="sfptemplate",
            name="line_type",
            field=models.CharField(
                choices=[
                    ("None", "None"),
                    ("single-mode", "Одномодовый"),
                    ("multi_mode", "Многомодовый"),
                    ("Ethernet", "Медный провод"),
                ],
                verbose_name="Тип линии",
            ),
        ),
    ]
