# Generated by Django 5.0.7 on 2024-09-07 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0055_alter_access_role_alter_equipmenttemplate_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="access",
            name="role",
            field=models.CharField(
                choices=[
                    ("Read", "Чтение"),
                    ("Creator", "Создатель"),
                    ("Change", "Изменение"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="equipmenttemplate",
            name="type",
            field=models.CharField(
                choices=[
                    ("Server", "Сервер"),
                    ("Passive", "Пассивное оборудование"),
                    ("Switch", "Коммутатор"),
                ],
                max_length=100,
                verbose_name="Тип оборудования",
            ),
        ),
        migrations.AlterField(
            model_name="port",
            name="line_type",
            field=models.CharField(
                choices=[
                    ("multi_mode", "Многомодовый"),
                    ("None", "None"),
                    ("Ethernet", "Медный провод"),
                    ("single-mode", "Одномодовый"),
                ],
                max_length=100,
                null=True,
                verbose_name="Тип линии",
            ),
        ),
        migrations.AlterField(
            model_name="port",
            name="vlan_type",
            field=models.CharField(
                choices=[("Trunk", "Trunk"), ("Access", "Access"), ("None", "None")],
                max_length=100,
                null=True,
                verbose_name="Тип vlan",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="type",
            field=models.CharField(
                choices=[("Regular", "Обычная"), ("Server", "Серверная")],
                max_length=100,
                verbose_name="Тип комнаты",
            ),
        ),
        migrations.AlterField(
            model_name="sfptemplate",
            name="line_type",
            field=models.CharField(
                choices=[
                    ("multi_mode", "Многомодовый"),
                    ("None", "None"),
                    ("Ethernet", "Медный провод"),
                    ("single-mode", "Одномодовый"),
                ],
                verbose_name="Тип линии",
            ),
        ),
    ]
