# Generated by Django 5.1.1 on 2024-12-05 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0057_alter_access_role_alter_equipmenttemplate_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LineModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Line",
                "verbose_name_plural": "Lines",
                "db_table": "lines",
            },
        ),
        migrations.CreateModel(
            name="LineTypeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Line type",
                "verbose_name_plural": "Lines types",
                "db_table": "line_types",
            },
        ),
        migrations.AlterField(
            model_name="port",
            name="connection",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="connection_port",
                to="models_app.port",
            ),
        ),
        migrations.AlterField(
            model_name="port",
            name="connection_pigtail",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="connection_pig",
                to="models_app.port",
            ),
        ),
        migrations.AlterField(
            model_name="port",
            name="ip",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="IP адрес"
            ),
        ),
        migrations.AlterField(
            model_name="port",
            name="line_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("single-mode", "Одномодовый"),
                    ("multi_mode", "Многомодовый"),
                    ("Ethernet", "Медный провод"),
                    ("None", "None"),
                ],
                max_length=100,
                null=True,
                verbose_name="Тип линии",
            ),
        ),
        migrations.AlterField(
            model_name="port",
            name="mac",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Mac адрес"
            ),
        ),
        migrations.AlterField(
            model_name="port",
            name="sfp",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="port",
                to="models_app.sfptemplate",
                verbose_name="Sfp",
            ),
        ),
        migrations.AlterField(
            model_name="port",
            name="vlan",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Vlan на котором работает порт"
            ),
        ),
        migrations.AlterField(
            model_name="port",
            name="vlan_type",
            field=models.CharField(
                blank=True,
                choices=[("Access", "Access"), ("Trunk", "Trunk"), ("None", "None")],
                max_length=100,
                null=True,
                verbose_name="Тип vlan",
            ),
        ),
        migrations.AlterField(
            model_name="porttemplate",
            name="name",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Наименование"
            ),
        ),
        migrations.AlterField(
            model_name="porttemplate",
            name="type_port",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="port_template",
                to="models_app.typeport",
                verbose_name="Тип порта",
            ),
        ),
        migrations.AddField(
            model_name="port",
            name="line",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ports",
                to="models_app.linemodel",
            ),
        ),
        migrations.AddField(
            model_name="linemodel",
            name="line_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lines",
                related_query_name="line",
                to="models_app.linetypemodel",
            ),
        ),
    ]
