# Generated by Django 5.1.1 on 2024-12-05 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0058_linemodel_linetypemodel_alter_port_connection_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipmenttemplate",
            name="is_active",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="linemodel",
            name="filled_line",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
