name: Run Django Tests with Docker Compose

on:
  push:
    branches:
      - testing

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: mydatabase
      DB_PORT: 5435
      DB_HOST: postgres
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and run Docker Compose
        run: |
          docker-compose -f docker-compose.yml up --build -d
          sleep 10
          docker-compose -f docker-compose.yml logs
          docker-compose -f docker-compose.yml exec -T web pipenv run python manage.py test
          docker-compose -f docker-compose.yml down