name: Run Django Tests with Docker Compose

on:
  push:
    branches:
      - testing

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run command and remote server
        uses: D3rHase/ssh-command-action@v0.2.2
        with:
          host: ${{secrets.SSH_HOST}}
          user: ${{secrets.SSH_USER}}
          private_key: ${{secrets.SSH_PRIVATE_KEY}}
          command: |
            echo '--- START WORK ON REMOTE SERVER ---';
            cd ${{ secrets.PROJECT_FOLDER }};
            echo '--- LIST OF FILES ---';
            git checkout testing;
            git pull;
            cp .env-example .env;
            ls -a;
            docker compose down;
            echo '--- LIST OF DOCKER CONTAINERS AFTER STOPING DOCKER CONTAINERS ---';
            docker compose up -d;
            echo '--- LIST OF DOCKER CONTAINERS AFTER STARTING DOCKER CONTAINERS ---';
            docker ps;
